name: Weather Checker

on:
  schedule:
    # каждый час
    - cron: "0 * * * *"
  workflow_dispatch:  # ручной запуск

jobs:
  check_weather:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Клонируем репозиторий
      - uses: actions/checkout@v4

      # 2️⃣ Устанавливаем Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3️⃣ Устанавливаем зависимости
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4️⃣ Запускаем скрипт погоды
      - name: Run weather script
        run: python weather.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL: ${{ secrets.CHANNEL }}
